apiVersion: apps/v1
kind: Deployment
metadata:
  name: doralearning
  labels:
    app: doralearning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doralearning
  template:
    metadata:
      labels:
        app: doralearning
    spec:
      containers:
        - name: doralearning
          image: 127486921697.dkr.ecr.eu-west-1.amazonaws.com/doralearning:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080